name: Build KirkOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    name: Linux (.deb)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Build .deb
        shell: bash
        run: >
          jpackage
          --type deb
          --input .
          --main-jar kirkos.jar
          --name kirkos
          --app-version 1
          --vendor "K.I.R.K SYSTEMS"

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: kirkos-linux-deb
          path: "*.deb"

  windows:
    name: Windows (.exe)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Build .exe
        shell: pwsh
        run: >
          jpackage
          --type exe
          --input .
          --main-jar kirkos.jar
          --name kirkos
          --app-version 1
          --vendor "K.I.R.K SYSTEMS"
          --win-console

      - name: Upload .exe
        uses: actions/upload-artifact@v4
        with:
          name: kirkos-windows-exe
          path: "*.exe"
